### PR TITLE
Add function to enable updating firmware offline

### PR DESCRIPTION
**Pull request by HappyZ**

### CODE REVIEW

**Comment by HappyZ** [comment]
Tested with the current update pkg file.

**Comment by janten** [comment]
What a great addition, thank you!

**Comment by Sfinx** [comment]
Hi,

Where to the this PKG file ? Can it be downloaded from official site ? or copied from some digipaper folder ?

**Comment by HappyZ** [comment]
Here is the link where you can download the original pkg:
```
<Distribution 
  ID="Firmware"
  InstallParams="" 
  InstallType="binary" 
  MAC="b13e781d7f6be196041421da629c375b" 
  Size="229463654" 
  Type="" 
  URI="https://www.sony.net/Products/DigitalPaperSystem/Software/DP/FwUpdater.pkg" 
  Version="1.4.01.16100"/>
```

**Comment by Sfinx** [comment]
Thanks ! The last question ;) Where I can get this removed from github files like start_eufwupdater.sh and so on ?

**Comment by HappyZ** [comment]
what you mean? `start_eufwupdater.sh` you can found it online actually.

**Comment by HappyZ** [comment]
@janten I have been thinking and reading the reversed code and below are several thinking directions
1) testmode needs special private key to enable - wait till RSA public key can be broken (if finding primes for it, which is highly unlikely)
2) pkg can be unpacked/packed but again require an 2048-bit RSA key to sign - dead road probably
3) finding security vulnerabilities in reslet framework 2.3.12
4) preventing usb ethernet mode + enabling adb
5) ?
I don't have much time for 3) and 4) or 5) now, but if you have more thoughts discussions are welcome.

**Pull request merged**
