### PR TITLE
Small fixes and improvements to dptmount

### PR DESCRIPTION
**Pull request by mezzarobba**
Hi,

Thank you very much to you and all contributors for this very useful tool!

I had to make some small changes to be able to use the Fuse filesystem. These patches have worked well for me for a couple of months now. They are far from perfect, but I thought they could still be an improvement for other people.

Note that, after rebasing, the last of the patches basically reverts https://github.com/janten/dpt-rp1-py/pull/95 (originally developed in parallel) in favor of a different approach. I hope my version really fixes the corresponding issue. (@hisaknown, what do you think?)

### CODE REVIEW

**Comment by hisaknown** [comment]
Thank you for mentioning!

I haven't check whether your patch works for me yet, but it is ok for me to revert #95.  
I would comment here once I confirmed your patch works on my environment.

**Comment by janten** [comment]
Could you have a look at the merge conflict, @mezzarobba?

**Comment by mezzarobba** [comment]
On Wednesday, 15 April 2020 01:26:26 CEST Jan-Gerd Tenberge wrote:
> Could you have a look at the merge conflict, @mezzarobba?

Thank you for the notice.

I think all the conflicts are with the automated(?) formatting changes 
you did in a2ec98. So I (essentially) rebased -X theirs my branch on top 
of master, and the result seems to work. But I suppose you may want to 
re-run the formatter on dptmount.py.

Best,

-- 
Marc

**Comment by janten** [comment]
Merged!

**Comment by hisaknown** [comment]
Thank you for merging and I'm sorry that I couldn't check the code.  
Actually my working environment (for `dptmount`) is at my office, where I can't go due to the corona virus.

**Comment by mezzarobba** [comment]
On Saturday, 9 May 2020 10:31:30 CEST Jan-Gerd Tenberge wrote:
> Merged!

Thank you!

-- 
Marc

**Pull request merged**
