### PR TITLE
Improve synchronization

### PR DESCRIPTION
**Pull request by hakon-j-d-johnsen**
Hi Jan-Gerd,

This PR contains some improvements to the sync command. 

**Sync confirmation**
Commit e98e87a8e25862c7abf5332ddde9d76f51acf514 shows the user a summary of the number of files that will be transferred/deleted. In this way, the user will hopefully notice if he has made an error, so that the action (and potential data loss) can be aborted. 

A few things to think about here:
 - This change is not fully backward compatible, since syncing is no longer non-interactive. If the user has set up a cron job to sync automatically, this will no longer work. However, I think it is not too unreasonable to break backward compatibility since the sync functionality is new and experimental. Adding a command-line flag for noninteractive mode might be useful for cron jobs and the like, but I did not prioritize it for now.
 - The confirmation check happens in the dptrp1 module, not in the CLI module. It seems like you have a fairly clean separation between the library and the CLI, and this breaks that separation to a certain extent. I personally don't think it is a big problem, but feel free to let me know if you would like it to be organized differently.

**Syncing on Windows**
Commit 8a687742a5d62d5ad086a4819695513302f68ced normalizes the directory separator being used in the sync logic, to fix syncing on Windows. This is done using simple string replacement. It would probably be cleaner to do it all using pathlib or something, but this approach was a quick and easy fix. Tested on Windows and Linux.

**Progress bar**
Commit d747b4a4e4548088801fb658e5b808cd2bf6bb81 shows some additional progress information, including a tqdm progress bar. This adds an extra dependency, but tqdm is a popular library and I think the improved usability is worth the extra dependency.

Feel free to let me know if you want any of these things to be done differently. The changes are atomic, so you can also cherry-pick just 1 or 2 if you don't want to merge them all.

Best,
Håkon

### CODE REVIEW

**Comment by hakon-j-d-johnsen** [comment]
This PR is now rebased on the current master.

I have also been working on some additional sync improvements, currently residing in my own [experimental-sync](/hakon-j-d-johnsen/dpt-rp1-py/tree/experimental-sync) branch. Those changes are not yet fully ready for a PR, but I thought I would let you know that I am working on them. It is also fine if you want to postpone applying this PR until the additional improvements are ready.

The new changes are mainly about revamping the sync algorithm to improve performance with large libraries. For my own library of 582 PDFs, the experimental changes reduce sync time from 39 seconds to 2.6 seconds (over wifi).

**Comment by yunjae2** [comment]
I had to wait for a long time when syncing with new desktop, so the performance improvement looks very interesting.

**Comment by hakon-j-d-johnsen** [comment]
> Can you add a `--force` option to skip the interactive part?
No problem, I will have a look at it over the weekend or next week.

**Comment by janten** [comment]
Are you still working on this and your experimental-sync branch, @hakon-j-d-johnsen? I am personally very much interested in faster syncing, though the missing non-interactive break my use-case of automatic syncing to my Raspberry.

**Comment by hakon-j-d-johnsen** [comment]
Sorry for forgetting about this, @janten. I didn't get around to this, due to a lack of time and because it was working well enough for my own use-case. I will add a --force option and polish the faster syncing this weekend.

**Comment by hakon-j-d-johnsen** [comment]
I've gone through and did some polishing on the experimental sync changes, and included them into this PR.

Some remarks:
* There is now a `--yes` flag for non-interactive synchronization (similar to apt-get's --yes flag). Feel free to ask for this to be changed to `--force` if you prefer that.
* The updated sync logic is generally based on the choices made in the existing sync logic (for handling things such as conflicts, etc), but I've tried to make it more explicit how each special case should be treated.
* There is still some technical debt from the previous sync logic:
  * Synchronization checkpoints are still simply a pickle-dump of the files/folders on the DPT at an earlier point in time. Some other format might be beneficial, but would break compatibility.
  * Since the checkpoints only contain data from the device, we still depend on the clocks to be somewhat synced. This should not be too much work to fix, but I've not prioritized it for now.
* Ideally, there should also be some unit tests here, especially because syncing is not completely straightforward and it's easy to get some edge case wrong. I unfortunately don't have time to add that atm.

**Comment by NicolasHug** [comment]
This seems to be exactly what I wanted, thanks!
I've used this with basic workflow and it seems to work as expected.

Minor suggestions:

- maybe make the "list" option more obvious, e.g. replace "?" by "list" in the prompt. Or maybe even just print by default before a y/n prompt.
- The "Documents" folders seems to always be in the `folders_to_create_remote` list, even when no changes happen. That's a bit scary at first since it seems to suggest that the whole folder will be overridden on the device.

**Comment by janten** [comment]
Thanks for the contribution, @hakon-j-d-johnsen. I am going to merge this as it is. @NicolasHug, please feel free to add your suggested improvements in a separate PR.

**Pull request merged**
