### PR TITLE
More functionality, including registration

### PR DESCRIPTION
**Pull request by bpteague**
Hi @janten -

First, thanks for the initial work on making the DPT-RP1 work on other operating systems.  Without your efforts, we'd be nowhere.

Since your project is what shows up when people search for "DPT-RP1 on linux", I hope you'll consider merging this PR.  There are three major additions:

- I've merged @farhaven's translations of the endpoints JSON file, which are a great staring point for adding more functionality

- I've split the command-line interface out into its own file, with the eventual goal of writing a more complete sync application around the "dpt-rp1.py" API

- Finally -- REGISTERING WORKS!  I managed to translate the javascript in the Sony app to Python, and now (if you use Bluetooth for networking), you can take Windows and MacOS entirely out of the picture.

Thanks for your consideration!
Brian

### CODE REVIEW

**Comment by janten** [comment]
Hi Brian,

Happy New Year and thank you for this huge contribution!

**Comment by farhaven** [comment]
There might be a small caveat wrt the endpoints JSON file though: I took that file from a dump of the `.apk` files on the device itself. Except for the translations, which are almost completely Google Translate's work, the file was left as-is.

I live in Germany and as far as I understand German law, providing information that is used for reverse engineering is legal. I am not sure how US law or the law in other places sees that. AFAIK, almost all EU countries handle this similar to Germany.

This might mean that the `endpoints.json` file has to be removed (maybe even retroactively) from the Git history if someone files a DMCA complaint or similar. I am fine with risking Github removing my own fork of the repo FWIW.

**Comment by janten** [comment]
I also live in Germany and decided not to provide a manipulated version of the Digital Paper App for this reason. Maybe we can remove the _endpoints.json_ file and add some information to the readme on how the extract the file from the device itself?

**Comment by bpteague** [comment]
Hrm. I Am Not A Lawyer, but my understanding of the DMCA is that it disallows production and distribution of technologies that circumvent measures protecting access to copyrighted works.  For example, if the software let you break Amazon's Kindle encryption and share Kindle ebooks, that would be illegal.

On the other hand, this may fall under plain old copyright law.  Sony may consider the endpoints.json file their intellectual property, and may argue that we do not have the right to distribute it.  The same would apply to distributing a modified version of the Digital Paper App.

Finally, instructions for extracting that file from the device is reverse engineering.  Which, despite some American law-makers' attempts, is still legal in the US.  Also, I haven't seen anything on the internet about extracting anything from the device, and would be very interested in that info. This is a super-cool piece of hardware and I would love to extend its capabilities by making it easier to get documents on and off of it (WebDAV sync, for example, or figuring out what a "control server" is and does.)

**Comment by farhaven** [comment]
Okay, that sounds like we'll keep it in the repos until someone complains and then comply with their demands. Sounds reasonable.

As for pulling the APK from the device, I didn't do the pulling myself. Apparently an enterprising hacker somewhere in China sells RP1s which can run 3rd party apps and a customer of theirs dumped all APKs. Googling for something like "sony dpt rp1 root" yields 
a thread in a relatively well-known forum for XDA developers, which contains a link to the APKs.

**Pull request merged**
