### PR TITLE
Gui

### PR DESCRIPTION
**Pull request by bpteague**
Hi @janten - This PR implements a basic GUI.  A few details:
- The GUI is based on `pyface`, which can draw a UI using either Qt or Wx.  At the moment I'm using Qt, because it's more widely available.
- The GUI needed a slightly more object-oriented view of the DPT-RP1, so I've changed the `DigitalPaper` API a bit. The CLI is updated as well.

Let me know what you think.  Feedback is appreciated!

### CODE REVIEW

**Comment by bpteague** [comment]
Ooof.  Don't merge this yet, I just discovered a gnarly bug.

**Comment by bpteague** [comment]
Okay.  Fixed an issue that I introduce while porting my API changes over to this branch.  Should be good to go.

**Comment by janten** [comment]
Hi @bpteague, could you rebase this to the current master branch?

**Comment by bpteague** [comment]
Sure -- but I probably won't get to it until this weekend.

**Comment by bpteague** [comment]
Lemme fix that TravisCI check. Hold on.

**Comment by bpteague** [comment]
Alright, this is ready to go.  A few notes:
 - The GUI requires either Qt4 or Qt5, AND one of the Python Qt APIs.  Both the Qt libraries and the Python API need to be installed using either an OS-level package manager (like `brew` or `apt get`), or using a Python distribution like Anaconda
- The `dptrp1` package will still install without these things, so the CLI is usable without the GUI.  If you try to start the GUI and it can't find and load a Qt API, it fails with an informative message.
- As I mentioned above, the GUI required a somewhat more object-oriented view of the DPT-RP1 device, so the API has changed pretty considerably. I imagine this will be a better interface for people who, say, want to implement a FUSE module on top of this.

Have a look and let me know what you think!

**Comment by cypresstwist** [comment]
Trying to launch it but I get this error:

```
python3 /usr/local/bin/dptrp1-gui
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1-gui", line 4, in <module>
    __import__('pkg_resources').run_script('dpt-rp1-py==0.2.0', 'dptrp1-gui')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/dpt_rp1_py-0.2.0-py3.6.egg/EGG-INFO/scripts/dptrp1-gui", line 6, in <module>
    from dptrp1.gui.run import main
ModuleNotFoundError: No module named 'dptrp1.gui'
```

**Comment by janten** [comment]
Since this script originally started out as my private endeavor to sync my reader without using a GUI interface, a GUI should probably live in its own repository and just list the dpt-rp1-py package as a dependency. Should you go that route, please add a link to your project to the Readme and file a new PR for that.

**Pull request closed without merging**
